### ISSUE TITLE
Cross-platform

### ISSUE THREAD

**Issue by malakar-soham** [malakar-soham/ez#52]
**Task**<br>
Make the website cross platform

**Description**
- Make the website cross-platform
- Currently the website shows all functionalities in:
- [x] Google Chrome (tested)
- [x] Vivaldi (tested)
- [x] Microsoft Edge (tested)
- [ ] Mozilla Firefox browser (tested)
- [ ] Safari

**Branch**<br>
Please put the PR in `gh-pages-dev` branch
